# Generated by Django 4.2.11 on 2024-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quizattempts_total_numericalanswered_mcqanswered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
