# Generated by Django 4.2.11 on 2024-03-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_quiz_coding_alter_quiz_mcqs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqquestions',
            old_name='quiz',
            new_name='quiz_id',
        ),
    ]
