# Generated by Django 4.2.11 on 2024-03-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_quiz_mcqquestions_quiz_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqquestions',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
