# Generated by Django 4.2.11 on 2024-03-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_codingquestions_alter_mcqoptions_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestions',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codingquestions',
            name='quiz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.quiz'),
            preserve_default=False,
        ),
    ]
