# Generated by Django 4.2.11 on 2024-04-07 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_mcqanswered_quiz_numericalanswered_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='codinganswered',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.quiz'),
        ),
    ]
