# Generated by Django 4.2.11 on 2024-04-08 21:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_rollnumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RollNumber',
            new_name='userProfile',
        ),
    ]
