# Generated by Django 4.2.11 on 2024-04-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_rollnumber_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roll',
            field=models.IntegerField(unique=True),
        ),
    ]
