# Generated by Django 4.2.11 on 2024-04-08 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_userprofile_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case', models.CharField(max_length=5000)),
                ('expected_output', models.CharField(max_length=5000)),
                ('marks', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.codingquestions')),
            ],
        ),
        migrations.CreateModel(
            name='CodeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=5000)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testcases')),
            ],
        ),
    ]
