# Generated by Django 4.2.11 on 2024-04-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_testcases_codeoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestions',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
