# Generated by Django 4.2.11 on 2024-04-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_codingquestions_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='test_case',
            new_name='input',
        ),
        migrations.AddField(
            model_name='codingquestions',
            name='example_input',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='codingquestions',
            name='example_output',
            field=models.CharField(default='', max_length=500),
        ),
    ]
