# Generated by Django 4.2.11 on 2024-04-10 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delete_codeoutput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestions',
            name='marks',
        ),
    ]
