# Generated by Django 4.2.11 on 2024-04-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_suspiciousactivity_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCasesOutputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=5000)),
                ('score', models.IntegerField(default=0)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testcases')),
            ],
        ),
    ]
