from django.urls import path, include
from .views import createQuiz, addMCQquestion, addMCQoption, addNumericalQuestion, addNumericalAnswer, save_responses, get_quizes, get_questions, get_quiz, delMCQquestion, delNumericalQuestion, delQuiz, check_attempted, add_coding_question, delCodingQuestion, numCod, compute_result, run_code, save_code, run_saved_code, submit_code_quiz, check_superuser, add_suspicious_activity, add_roll_number, get_result_all, check_roll_number, add_test_case, delete_test_case, get_test_cases, get_coding_question, get_suspicious_activity, get_saved_code, editQuiz, edit_coding_question, edit_test_case, get_test_case, edit_mcq_option, edit_mcq_question, edit_numerical_question, get_mcq_question, get_mcq_answer, get_numerical_question, get_result_test_cases, get_questions_with_answers

urlpatterns = [
    path('createQuiz/', createQuiz),
    path('editQuiz/', editQuiz),
    path('addMCQquestion/', addMCQquestion),
    path('addMCQoption/', addMCQoption),
    path('addNumericalQuestion/', addNumericalQuestion),
    path('addNumericalAnswer/', addNumericalAnswer),
    path('save_responses/', save_responses),
    path('get_quizes/', get_quizes),
    path('get_quiz/', get_quiz),
    path('get_questions/', get_questions),
    path('delnum/', delNumericalQuestion),
    path('delmcq/', delMCQquestion),
    path('delquiz/', delQuiz),
    path('check_attempted/', check_attempted),
    path('add_coding_question/', add_coding_question),
    path('del_coding_question/', delCodingQuestion),
    path('numCod/',numCod),
    path('compute_result/', compute_result),
    path('run_code/', run_code),
    path('save_code/', save_code),
    path('run_saved_code/', run_saved_code),
    path('submit_code_quiz/', submit_code_quiz),
    path('check_superuser/', check_superuser),
    path('add_suspicious_activity/', add_suspicious_activity),
    path('add_roll_number/', add_roll_number),
    path('check_roll_number/', check_roll_number),
    path('get_result_all/', get_result_all),
    path('add_test_case/', add_test_case),
    path('delete_test_case/', delete_test_case),
    path('get_test_cases/', get_test_cases),
    path('get_coding_question/', get_coding_question),
    path('get_suspicious_activity/', get_suspicious_activity),
    path('get_saved_code/', get_saved_code),
    path('edit_coding_question/', edit_coding_question),
    path('edit_test_case/', edit_test_case),
    path('get_test_case/', get_test_case),
    path('edit_mcq_question/', edit_mcq_question),
    path('edit_mcq_option/', edit_mcq_option),
    path('edit_numerical_question/', edit_numerical_question),
    path('get_mcq_question/', get_mcq_question),
    path('get_numerical_question/', get_numerical_question),
    path('get_mcq_answer/', get_mcq_answer),
    path('get_result_test_cases/', get_result_test_cases),
    path('get_questions_with_answers/', get_questions_with_answers),
]
